### ISSUE TITLE
Kadish Alt Vault step colliders cause toe stubs

### ISSUE THREAD

**Issue by ZarothYe** [H-uru/moul-assets#163] opened 2022-07-04 02:34 UTC
From TL, where collision angle limit is 55 degrees. Several/most steps are much too steep of a collision for the avatar to walk up. Most registering between 60-80 degrees.

![image](https://user-images.githubusercontent.com/94947971/177071348-5bf8acec-9ea4-4d17-af06-613fa9616608.png)

Regular Kadish vault is smoooth; no stubs to be found. Yay!
![image](https://user-images.githubusercontent.com/94947971/177071591-e6d4ca80-a2c7-4033-b1a3-8fb980564fae.png)

**Comment by Hoikas** [comment] 2022-07-04 02:47
Duplicate of #43.

**Closed by Hoikas** 2022-07-04 02:47 UTC
